// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardsShowController from "./cards_show_controller"
application.register("cards-show", CardsShowController)

import FilterListController from "./filter_list_controller"
application.register("filter-list", FilterListController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
